version: '2'
services:
  web-pozos:
    image:  php:apache
    depends_on:
      - api
    ports:
      - "8081:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - api-pozos-network

  api-pozos:
    image: api-pozos:1
    ports:
      - "5001:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api-pozos-network

networks:
  api-pozos-network:
